name: Test
run-name: Test ${{ github.ref_name }} triggered by @${{ github.actor }}

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up go
      uses: actions/setup-go@v5
      with:
        go-version-file: go.mod

    - name: Test
      run: go test -v ./... -coverprofile=cover.out

  test-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Test
        run: go test -v ./... -coverprofile=cover.out
